#!/bin/bash

echo "Run wrapper"


export GEM_HOME=/usr/local/bundle
export BUNDLE_APP_CONFIG=/usr/local/bundle
export PATH=/usr/local/bundle/bin:$PATH
export RUBY_MAJOR=2.2
export RUBY_VERSION=2.2.1

ls -l
pwd
ls -l bosh-init-manifests/idefixoperationsinfratest-deploymenttest/
ls -l bosh-init-manifests/

bdr_out
